theme: minima
title: Rachel Girgis' Website
author: Rachel Girgis
email: Rgirgis3@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  This is an online portfolio of Rachel Girgis. 

# social links
twitter_username: Rgirgis3
github_username:  Rgirgis33

show_excerpts: true # set to false to remove excerpts on the homepage
