theme: minima 
title: Rachel Girgis
author: Rachel Girgis
email: rgirgis@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
This website is so cool! 

# social links
instagram_username: _rachel.anne.g_
github_username:  Rgirgis33

show_excerpts: true # set to false to remove excerpts on the homepage
